export const PAYMENT_PROCESS_REQUEST = 'PAYMENT_PROCESS_REQUEST';
export const PAYMENT_PROCESS_SUCCESS = 'PAYMENT_PROCESS_SUCCESS';
export const PAYMENT_PROCESS_FAIL = 'PAYMENT_PROCESS_FAIL';

export const PAYMENT_VERIFY_REQUEST = 'PAYMENT_VERIFY_REQUEST';
export const PAYMENT_VERIFY_SUCCESS = 'PAYMENT_VERIFY_SUCCESS';
export const PAYMENT_VERIFY_FAIL = 'PAYMENT_VERIFY_FAIL';