export const RECOMMENDATION_LIST_REQUEST = 'RECOMMENDATION_LIST_REQUEST';
export const RECOMMENDATION_LIST_SUCCESS = 'RECOMMENDATION_LIST_SUCCESS';
export const RECOMMENDATION_LIST_FAIL = 'RECOMMENDATION_LIST_FAIL';

export const RECOMMENDATION_CATEGORY_REQUEST = 'RECOMMENDATION_CATEGORY_REQUEST';
export const RECOMMENDATION_CATEGORY_SUCCESS = 'RECOMMENDATION_CATEGORY_SUCCESS';
export const RECOMMENDATION_CATEGORY_FAIL = 'RECOMMENDATION_CATEGORY_FAIL';